language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: cSaqZKwYDpOH7yyr2nuUuma2t7yaQTK8tkccBJkHjdmomIblr+zzOuTYSTAtQDflptmPyLXNT0AON6drXeo94iJ60dZ7DVNf1GCnmxzreZfK+ipGu5ruBnDV58Qa+lmS4YWjT7Iffck1X9sSsXVyxQ6p+gsjmSVZ9T5nMeDGBepe4S4DZdeVZzEO0tFXN57WtyZnMxkHW1bgB6nNQHy8y/icg8tniwhuGT0WkGIFckK6gNSLpkGIW+APxxDM8c0qmXpeJQwr19sbN5/SYGWp8Ri2B06gn/7LB3n1TCTQgwV3MUcf6Kd92ObJTFcGN3IFfXARFpJTHphyuBwpIeMLY1E7Z93SeWU9YkZhsjSoUN8yUA9fc9FMoqhc/vvAgCS4bFYkeONtbeV9bdXB4S5wvwzvXmLr5OSjj2F22QKAdoFb/tv02RkuhW0jc48CXumAu1TS5kx7cSvvr9Pxo8YETeppZnRQ0/3KtBkEl4Vw6Bq00zoa9qXggnZ1PXUIKC7LgYfAHHN+ljLqKH7vRVWFlQifj4qnM/d4gDWwplV1z1SzW7YtU1h4JJgXA5q/LiT2iyRLPXJNlH3m49kH4KcR7RQ4+KO07mAc7BPccm3gXtV8sPr0/tWmjf+UGzwqZ0q22OLFkd4CFFRVFq04ckzE53cCVVqvU4PRQQuDk7Jb8gg=
  app: website-gallery
  skip-cleanup: true
  on:
    repo: jennifer/gallery
